version: "3.9"
services:
    # postgres:
    #     container_name: postgres_db
    #     image: postgres
    #     restart: always
    #     environment:
    #         - POSTGRES_USER = postgres
    #         - POSTGRES_PASSWORD = postgres
    #         - POSTGRES_DB = postgres
    #     ports:
    #         - 5432:5432
    mongo:
        image: mongo
        restart: always
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
        - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/